### ISSUE TITLE
Running on imagery pairs?

### ISSUE THREAD

**Issue by dbonafilia** [Kai-46/VisSatSatelliteStereo#12]
Hi!

I've been able to get this working for the IARPA MVS dataset, but if I attempt to run it on just two images, it fails out, seeming to not be able to find any matches. 

Did you have to change any settings to get this to work on only 2 images for your evaluations in the paper?

here's my what my logs look like at the point where it cant match and triangulate:

==============================================================================

Loading database

==============================================================================

Loading cameras... 2 in 0.000s

Loading matches... 1 in 0.000s

Loading images... 2 in 0.006s (connected 2)

Building correspondence graph... in 0.001s (ignored 0)

Elapsed time: 0.000 [minutes]

0001_WV03_15MAY05_140810-P1BS-500497282090_01_P001.png, 6400

0000_WV03_15APR03_140238-P1BS-500497283030_01_P001.png, 6400

==============================================================================

Triangulating image #1

==============================================================================

  => Image has 0 / 6400 points

  => Triangulated 0 points

==============================================================================

Triangulating image #2

==============================================================================

  => Image has 0 / 6400 points

  => Triangulated 0 points

  => Merged observations: 0

  => Completed observations: 0

**Comment by DieProgrammIDE** [comment]
I have the same problem

**Comment by DieProgrammIDE** [comment]
@dbonafilia Have you found a solution yet?

I have this error instead ...
But it is also a imagery pair.
`(vissat) root@2339a88e4468:/danesfield/tools# python3 /VisSatSatelliteStereo/stereo_pipeline.py --config_file /mnt/config.json 
{'dataset_dir': '/mnt/input', 'work_dir': '/mnt/output', 'bounding_box': {'zone_number': 33, 'hemisphere': 'N', 'ul_easting': 361907.62, 'ul_northing': 5810179.6, 'width': 7500, 'height': 7500}, 'steps_to_run': {'clean_data': False, 'crop_image': True, 'derive_approx': True, 'choose_subset': True, 'colmap_sfm_perspective': True, 'inspect_sfm_perspective': True, 'reparam_depth': True, 'colmap_mvs': True, 'aggregate_2p5d': True, 'aggregate_3d': True}, 'alt_min': -30.0, 'alt_max': 120.0}
step clean_data:	skipped
step crop_image:	finished in 0.0021876833333333333 minutes
step derive_approx:	finished in 0.002051883333333333 minutes
step choose_subset:	finished in 4.2999999999999995e-06 minutes
step colmap_sfm_perspective:	finished in 0.003976483333333333 minutes
/VisSatSatelliteStereo/debuggers/inspect_sfm.py:97: UserWarning: loadtxt: Empty input file: "/mnt/output/colmap/sfm_perspective/inspect_tri/kai_points.txt"
  self.points = np.loadtxt(os.path.join(self.out_dir, 'kai_points.txt'))
Traceback (most recent call last):
  File "/VisSatSatelliteStereo/stereo_pipeline.py", line 511, in <module>
    pipeline.run()
  File "/VisSatSatelliteStereo/stereo_pipeline.py", line 125, in run
    self.run_inspect_sfm_perspective()
  File "/VisSatSatelliteStereo/stereo_pipeline.py", line 373, in run_inspect_sfm_perspective
    sfm_inspector.inspect_all()
  File "/VisSatSatelliteStereo/debuggers/inspect_sfm.py", line 131, in inspect_all
    self.inspect_tracks()
  File "/VisSatSatelliteStereo/debuggers/inspect_sfm.py", line 224, in inspect_tracks
    reproj_errs = self.points[:, 3]
IndexError: too many indices for array
`
