### ISSUE TITLE
sqlite3.OperationalError: no such table: images

### ISSUE THREAD

**Issue by ujjawalcse** [Kai-46/VisSatSatelliteStereo#7]
I have only downloaded some PAN and MSI images (not completely) as you can seen below,

![ssr_msi](https://user-images.githubusercontent.com/32773256/119472302-c20f5d00-bd67-11eb-8ad5-ec8918ee878b.png)

![ssr_pan](https://user-images.githubusercontent.com/32773256/119472341-c9366b00-bd67-11eb-8714-19d2bfb95bc8.png)

Then I changed the path in the MVS3DM_Explorer.json and executed the code below ,

`python3 stereo_pipeline.py --config_file aoi_config/MVS3DM_Explorer.json`

```
{'dataset_dir': '/home/ujjawal/my_work/object_recon/SatelliteSurfaceReconstruction/satellite_imgs/WV3/PAN', 'work_dir': '/home/ujjawal/my_work/object_recon/SatelliteSurfaceReconstruction/VisSatSatelliteStereo/data2/kz298/explorer', 'bounding_box': {'zone_number': 21, 'hemisphere': 'S', 'ul_easting': 354052.3651180889, 'ul_northing': 6182702.10540914, 'width': 712.9748326897388, 'height': 651.4791190521792}, 'steps_to_run': {'clean_data': True, 'crop_image': True, 'derive_approx': True, 'choose_subset': True, 'colmap_sfm_perspective': True, 'inspect_sfm_perspective': False, 'reparam_depth': True, 'colmap_mvs': True, 'aggregate_2p5d': True, 'aggregate_3d': False}, 'alt_min': -30.0, 'alt_max': 120.0}
step clean_data:	finished in 0.010855866666666667 minutes
step crop_image:	finished in 0.04069456666666667 minutes
step derive_approx:	finished in 0.02496066666666667 minutes
step choose_subset:	finished in 1.0033333333333333e-05 minutes
Traceback (most recent call last):
  File "stereo_pipeline.py", line 511, in <module>
    pipeline.run()
  File "stereo_pipeline.py", line 115, in run
    self.run_colmap_sfm_perspective()
  File "stereo_pipeline.py", line 346, in run_colmap_sfm_perspective
    colmap_sfm_perspective.run_sfm(work_dir, sfm_dir, init_camera_file, weight)
  File "/home/ujjawal/my_work/object_recon/SatelliteSurfaceReconstruction/VisSatSatelliteStereo/colmap_sfm_perspective.py", line 72, in run_sfm
    reproj_err_threshold, reproj_err_threshold, reproj_err_threshold)
  File "/home/ujjawal/my_work/object_recon/SatelliteSurfaceReconstruction/VisSatSatelliteStereo/colmap_sfm_commands.py", line 75, in run_point_triangulation
    create_init_files(db_file, template_file, out_dir)
  File "/home/ujjawal/my_work/object_recon/SatelliteSurfaceReconstruction/VisSatSatelliteStereo/colmap_sfm_utils.py", line 110, in create_init_files
    table_images = db.execute("SELECT * FROM images")
sqlite3.OperationalError: no such table: images
```

Can you @Kai-46  please have a look into this issue?

**Comment by Kai-46** [comment]
Can you check if each step has run successfully by checking the log files and the output folder?

**Comment by ujjawalcse** [comment]
Yaa, I checked the logs, and I'm getting error in `colmap_sfm_perspective` step.

`Running subprocess: colmap feature_extractor --database_path /home/ujjawal/my_work/object_recon/SatelliteSurfaceReconstruction/VisSatSatelliteStereo/data2/kz298/explorer/colmap/sfm_perspective/database.db                                     --image_path /home/ujjawal/my_work/object_recon/SatelliteSurfaceReconstruction/VisSatSatelliteStereo/data2/kz298/explorer/colmap/sfm_perspective/images                                     --ImageReader.camera_model PERSPECTIVE                                     --SiftExtraction.max_image_size 10000                                      --SiftExtraction.estimate_affine_shape 0                                     --SiftExtraction.domain_size_pooling 1                                     --SiftExtraction.max_num_features 25000                                     --SiftExtraction.num_threads 32                                     --SiftExtraction.use_gpu 1                                     --SiftExtraction.gpu_index -1
ERROR: flag 'logtostderr' was defined more than once (in files 'src/logging.cc' and '/home/ujjawal/intrinsic3d/glog/src/logging.cc').

Subprocess finished
Running subprocess: colmap exhaustive_matcher --database_path /home/ujjawal/my_work/object_recon/SatelliteSurfaceReconstruction/VisSatSatelliteStereo/data2/kz298/explorer/colmap/sfm_perspective/database.db                                             --SiftMatching.guided_matching 1                                             --SiftMatching.num_threads 6                                             --SiftMatching.max_error 3                                             --SiftMatching.max_num_matches 30000                                             --SiftMatching.gpu_index -1
ERROR: flag 'logtostderr' was defined more than once (in files 'src/logging.cc' and '/home/ujjawal/intrinsic3d/glog/src/logging.cc').
`
Also, I couldn't get any log for `choose_subset` step.
 Is the step is skipped or logs are not saved for this ?

**Comment by Kai-46** [comment]
It seems to me that your colmap hasn't been installed properly. Can you check your colmap installation?
